//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public string ImageUrl { get; set; }
        public string ImageName { get; set; }
        public string ImageAlias { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Arrange { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
